### ISSUE TITLE
Issue in BusInfo.cs

### ISSUE THREAD

**Issue by harithlakmith** [harithlakmith/Public_Transport_Ticket_Booking-Team-08#13]
Please check again whether the data types of the fields are suitable.

You can compare with ER diagram shown in below,
<details>
<summary>ER Diagram</summary>
<br>
<img  src="https://user-images.githubusercontent.com/55950314/99075367-5e012480-25df-11eb-870d-a51521f95657.png" >
</details>

**Comment by lapalu1996** [comment]
Checked the data types of fields
